name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Set up mise
      uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
      with:
        version: 2025.12.13
        experimental: true
      env:
        # Adding token here to reduce the likelihood of hitting rate limit issues.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: go-cache-paths
      run: .github/scripts/go-cache-paths.sh

    - name: Go Build Cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: ${{ steps.go-cache-paths.outputs.go-build }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-linux-amd64

    - name: Go Mod Cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: ${{ steps.go-cache-paths.outputs.go-mod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}-linux-amd64

    - name: golangci-lint Cache
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: ~/.cache/golangci-lint
        key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/go.sum') }}-linux-amd64

    - name: Lint
      run: make lint

    - name: Test release scripts
      run: make test-scripts
