name: Pre-commit

on:
  workflow_call:

jobs:
  precommit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Use mise to install dependencies
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          version: 2025.12.13
          experimental: true
        env:
          # Adding token here to reduce the likelihood of hitting rate limit issues.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: go-cache-paths
        run: .github/scripts/go-cache-paths.sh

      - name: Go Build Cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}-linux-amd64

      - name: Run pre-commit hooks
        env:
          GOPROXY: direct
          GOOS: linux
          GOARCH: amd64
        run: pre-commit run --all-files
